import type { ProofType } from 'src/__generated__/graphql';

export type PROOF_KEY_VALUE_TYPE = ProofType;

export const PROOF_VALUES: Record<PROOF_KEY_VALUE_TYPE, string> = {
  SALE: 'SALE',
  PROFIT: 'PROFIT',
  INVOICE: 'INVOICE',
  OVERHEAD: 'OVERHEAD',
  PROMOTION: 'PROMOTION',
  LIQUIDITY: 'LIQUIDITY',
  COMMISSION: 'COMMISSION',
  DEVELOPERSWEB: 'DEVELOPERS:WEB',
  INFRASTRUCTURE: 'INFRASTRUCTURE',
  DEVELOPERSAPPS: 'DEVELOPERS:APPS',
  MINEELECTRICITY: 'MINE:ELECTRICITY',
  EXCHANGEFEE: 'MARKETING:EXCHANGE FEE',
  MINEMAINTAINANCE: 'MINE:MAINTAINANCE',
  MINENEWEQUIPMENT: 'MINE:NEW EQUIPMENT',
  DEVELOPERSPROTOCOL: 'DEVELOPERS:PROTOCOL',
  ADMINISTRATIONSALARY: 'ADMINISTRATION:SALARY',
  TRANSACTIONPROCESSING: 'TRANSACTION PROCESSING',
  MARKETINGTXCPROMOTION: 'MARKETING:TXC PROMOTION',
  DEVELOPERSINTEGRATIONS: 'DEVELOPERS:INTEGRATIONS',
  MINEFACILITYRENTMORTAGE: 'MINE:FACILITY RENT/MOTAGE',
  MARKETINGMINETXCPROMOTION: 'MARKETING:mineTXC PROMOTION',
};

export const MINE_LOCATION = [
  { label: 'GENERAL', value: 'General' },
  { label: 'MCKINNEY', value: 'McKinney' },
  { label: 'VICTORIA', value: 'Victoria' },
  { label: 'GONZALES', value: 'Gonzales' },
];
