import type { Proof } from 'src/sections/Proof/List/type';
import type { Member } from 'src/sections/Members/List/type';
import type { Package } from 'src/sections/Products/List/type';
import type { StatisticsSale } from 'src/sections/Statistics/type';

export type Sale = {
  __typename?: 'Sale';
  id: string;
  ID?: number | null;
  memberId: string;
  packageId: string;
  paymentMethod: string;
  proof?: Proof | null;
  member?: Member | null;
  toMember?: Member | null;
  package?: Package | null;
  statisticsSales?: Array<StatisticsSale> | null;
  status: boolean;
  isMetal: boolean;
  sponsorCnt: number;
  orderedAt: any;
  createdAt?: any | null;
  updatedAt?: any | null;
  deletedAt?: any | null;
};

export type BasicSale = {
  __typename?: 'BasicSale';
  id: string;
  ID: number;
  email: string;
  point: number;
  token: number;
  amount: number;
  createdAt: any;
  orderedAt: any;
  status: boolean;
  memberId: string;
  username: string;
  fullName: string;
  isMetal: boolean;
  sponsorCnt: number;
  productName: string;
  paymentMethod: string;
  assetId?: string | null;
  toEmail?: string | null;
  toMemberId?: string | null;
  toUsername?: string | null;
  toFullName?: string | null;
};
