import type { ProofType } from 'src/__generated__/graphql';

export type PROOF_KEY_VALUE_TYPE = Exclude<ProofType, ProofType.Prepay>;

export const PROOF_VALUES: Record<PROOF_KEY_VALUE_TYPE, string> = {
  COMMISSION: 'COMMISSION',
  ADMINISTRATIONSALARY: 'ADMINISTRATION:SALARY',
  INFRASTRUCTURE: 'INFRASTRUCTURE',
  MARKETINGMINETXCPROMOTION: 'MARKETING:mineTXC PROMOTION',
  MARKETINGTXCPROMOTION: 'MARKETING:TXC PROMOTION',
  MINEELECTRICITY: 'MINE:ELECTRICITY',
  MINEFACILITYRENTMORTAGE: 'MINE:FACILITY RENT/MOTAGE',
  MINEMAINTAINANCE: 'MINE:MAINTAINANCE',
  MINENEWEQUIPMENT: 'MINE:NEW EQUIPMENT',
  OVERHEAD: 'OVERHEAD',
  PROFIT: 'PROFIT',
  PROMOTION: 'PROMOTION',
  SALE: 'SALE',
  DEVELOPERSPROTOCOL: 'DEVELOPERS:PROTOCOL',
  DEVELOPERSWEB: 'DEVELOPERS:WEB',
  DEVELOPERSAPPS: 'DEVELOPERS:APPS',
  DEVELOPERSINTEGRATIONS: 'DEVELOPERS:INTEGRATIONS',
};
